# Data Acquisition

## Objetivos

1. Identificar el ciclo de vida de un proyecto de ciencia de datos.
2. Rastrear el origen de los datos y su uso.
3. Leer datos con `pandas`.

## 1. Librería `pandas`

En sesiones anteriores hemos realizado explorado la herramienta `pandas` para el procesamiento de datos, aquí veremos algunos ejemplos de su uso para la adquisición de datos de diversos formatos.

In [15]:
# Importar la librería
import pandas as pd

### 1.1. Lectura de archivos

La librería `pandas` permite manipular información de diversas fuentes. Con invocar un función, es posible transformar estas fuentes en objetos `Dataframe` dentro del entorno de Python.<br>

#### Importar archivos en formato `.csv`

Los archivos delimitados por comas o 'csv' son uno de los formatos de archivos más comunes en el procesamiento de datos.

In [16]:
# Cargar un dataframe con el archivo 'pune_1965_to_2002.csv'
df = pd.read_csv("pune_1965_to_2002.csv")
df.head()

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1965,0.029,0.069,0.000,21.667,17.859,102.111,606.071,402.521,69.511,5.249,16.232,22.075
1,1966,0.905,0.000,0.000,2.981,63.008,94.088,481.942,59.386,150.624,1.308,41.214,4.132
2,1967,0.248,3.390,1.320,13.482,11.116,251.314,780.006,181.069,183.757,50.404,8.393,37.685
3,1968,0.318,3.035,1.704,23.307,7.441,179.872,379.354,171.979,219.884,73.997,23.326,2.020
4,1969,0.248,2.524,0.334,4.569,6.213,393.682,678.354,397.335,205.413,24.014,24.385,1.951

In [17]:
# Leer archivo de datos "us_presidents 2.csv"
presidentes = pd.read_csv("us_presidents 2.csv")
presidentes.head()

,Unnamed: 0,S.No.,start,end,president,prior,party,vice
0,0,1,"April 30, 1789","March 4, 1797",George Washington,Commander-in-Chief of the Continental Army ...,Nonpartisan [13],John Adams
1,1,2,"March 4, 1797","March 4, 1801",John Adams,1st Vice President of the United States,Federalist,Thomas Jefferson
2,2,3,"March 4, 1801","March 4, 1809",Thomas Jefferson,2nd Vice President of the United States,Democratic- Republican,Aaron Burr
3,3,4,"March 4, 1809","March 4, 1817",James Madison,5th United States Secretary of State (1801–...,Democratic- Republican,George Clinton
4,4,5,"March 4, 1817","March 4, 1825",James Monroe,7th United States Secretary of State (1811–...,Democratic- Republican,Daniel D. Tompkins

In [18]:
presidentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  45 non-null     int64
 1   S.No.       45 non-null     int64
 2   start       45 non-null     object
 3   end         44 non-null     object
 4   president   45 non-null     object
 5   prior       45 non-null     object
 6   party       45 non-null     object
 7   vice        45 non-null     object
dtypes: int64(2), object(6)
memory usage: 2.9+ KB

#### Formato `.csv` con delimitador `;`

Cuando se tienen archivos su separador no es una `,` sino un `;`, se puede solucionar muy fácilmente usando `pandas` al establecer el delimitador.<br>
    
    read_csv(file = "nombre_archivo.csv", delimiter = ';')

In [19]:
# Cargar un dataframe con el archivo "DiccionarioPaises.csv"
pd.read_csv("DiccionarioPaises.csv", delimiter=";")

    País en español País en inglés
0        Afganistán    Afghanistan
1           Albania        Albania
2          Alemania        Germany
3           Andorra        Andorra
4            Angola         Angola
..              ...            ...
204         Vietnam        Vietnam
205           Yemen          Yemen
206          Yibuti       Djibouti
207          Zambia         Zambia
208        Zimbabue       Zimbabwe

[209 rows x 2 columns]

#### Importación de archivos en formato Excel `.xls` o `.xlsx`

Los archivos provenientes de MS-Excel puede ser fácilmente importado mediante `pandas` con una estructura similar a la siguiente:<br>
    
    read_excel(file = "nombre_archivo.xlsx")

In [20]:
# Cargar un dataframe con el archivo "ArchivoSoporteS3TU1.xlsx"
pd.read_excel("ArchivoSoporteS3TU1.xlsx")

      Nombre  Edad  Ingresos Ciudad Residencia
0       Juan    48        71            Bogotá
1      Maria    29       150              Lima
2      Jorge    43        98      Buenos Aires
3      Pablo    50       105            Bogotá
4      Laura    33        80            La Paz
5    Esteban    21       127              Lima
6    Juliana    48       131            La Paz
7  Valentina    47        89            Bogotá
8    Silvana    43       109      Buenos Aires

## 2. Ejemplos de aplicación

Aplicación del desafío genérico para el archivo de datos 'encuesta.txt'

In [21]:
# Cargar un dataframe con los datos del archivo 'encuesta.txt'
pd.read_csv('encuesta.txt', delim_whitespace=True, true_values=['si'], false_values=['no'], dtype={'asistio':bool, 'Tarea':bool})

                                  ID  asistio  Tarea  Comportamiento   Pago
0    cef3615d61b202f1dc794ef2746df14     True   True             0.0   True
1    323e5a13644d18185c743c241407754    False  False             NaN  False
2    b29a107e5cd062e654a63764157461d    False  False             NaN  False
3   04a11e4bcb573a1261eb0d9948d32637     True  False             0.0   True
4    9368291c3d5d5f5c8cdb1a575e18bec     True  False             0.0   True
5    dd0e77eab270e4b67c19b0d6bbf621b    False  False             NaN  False
6    7599c0aa419b59fd11ffede98a3665d    False  False             NaN   True
7    6dff182b452487f07a47596f314bddc    False   True             NaN   True
8    9dc233fed1c6eb2432672ab4bb39249    False  False             NaN  False
9   265fa78a1fb2409ff5416aec3c4f950d     True  False             0.0   True
10  3b461f95fe50be35b927c255b3f7dc3a     True   True             1.0  False
11  e786f1288887afb309eb913d28ffd6b0     True  False             0.0   True
12   10c74fd18bddfb3e26c1878a853e7f8     True  False             0.0   True
13   13b67c51d575bf29827debf0618b445     True  False             0.0   True
14   1f641566628797bf0f811701e818b2c     True   True             0.0   True
15  1ae10dc0d6fed06e8954af5f313cedf1    False  False             NaN   True
16  7dfbad6a32c7477604dea655327f20a2    False  False             NaN   True
17  b953218838a2f7057ec179cae0cf83ad     True  False             1.0   True
18  87fcfe4315ee8a3fb554d8bf608cb2ac     True  False             0.0   True
19  9b4935e514bdc9b66a35a085c229775c     True   True             0.0   True
20  8cf2a0f6b368a4a42572f775df0f5f90     True   True             1.0  False
21  b3d1716309461078c892edcd68db7d4c     True  False             0.0   True
22  be38b0df499caf723af579aa6b173b0a    False   True             NaN  False
23  97d2a0572f74acd8c4683ce7b72039db     True   True             0.0   True
24  4bfe54e669aa8eaf4c9db1b809f3b511    False  False             NaN  False
25  36f9d95975bfd2c89cfe75baca2d58d2     True  False             0.0   True
26  e886db962a67fdf6cddbd4e85ea5d6e6    False   True             NaN   True
27  212332278cfd07d49c4df986e6fbda1e     True   True             0.0   True
28  fb120d2658407cbedfd9f1136c94ac61     True  False             1.0   True
29  df891ef669fb23701f6622f14843bda2    False   True             NaN   True

Lectura de archivos `pickle`

In [22]:
# Leamos el archivo 'data.pkl'
pd.read_pickle('data.pkl')

UnpicklingError: invalid load key, '\x1f'.

Comparación de velocidad entre distintos tipos de archivos

## 3. Importación de multiples archivos a Python

Existen varias formas en las que podemos traer varios archivos al entorno de trabajo de `python`. Traigamos todos los dataframes de los archivos `.csv` corrientes.

### 3.1. Metodo exhaustivo

### 3.2. Metodo basado en los nombres

### 3.3. Metodo de inspección de entorno

In [ ]:
# Importe la libreria glob